# Generated by Django 5.0.2 on 2024-04-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_begin_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='begin_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_users',
        ),
    ]
